<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="TYSS-Amarnath" failures="1" tests="2" name="Test" time="18.068" errors="0" timestamp="2025-09-21T03:53:19 IST">
  <testcase classname="HRM_Framework.HRM_Framework.Login_Test" name="validLogin" time="5.005"/>
  <testcase classname="HRM_Framework.HRM_Framework.Login_Test" name="invalidLogin" time="3.912">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.com/web/index.php/auth/logi] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com/web/index.php/auth/logi] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]
at HRM_Framework.HRM_Framework.Login_Test.invalidLogin(Login_Test.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- invalidLogin -->
</testsuite> <!-- Test -->
